### ISSUE TITLE
Plugin rabbitmq_status.py not properly excluding notifications queues on returned metrics.

### ISSUE THREAD

**Issue by hybridpollo** [rcbops/rpc-openstack#1113]
Greetings,

I don't submit these very often,  it seems that this maybe the right place for this, otherwise then any guidance is always welcomed.   The maas plugin rabbitmq_status.py looks to not be properly excluding notification queues in the metrics reported.    Its possible this has to do with rabbitmq now using vhosts per each openstack component starting in 12.x.x.x implementations, but I will include as much  information as I can below.

##### What version (commit) do you encounter this issue on?

```
root@xxxxxx-infra01:/opt/rpc-openstack/rpcd# git describe --tags
r12.1.1
```

##### What type of issue is this (bug, feature, documentation, regression)?
Bug

##### What is the expected behavior?
rabbitmq_status.py properly excluding notification queues in the metrics.

##### What is actually happening?
MaaS alerts for rabbit are triggering with the following alarm, when all queues are at 0 except the notification.* queues:

REASON: RabbitMQ sum of queued messages excluding notifications queues is reaching configured limit. Currently above 100

##### How can we reproduce this issue?
Here is an example rabbitmq node with a growing notifications queue on the /ceilometer vhost.

```
root@xxxxxx-Infra01_rabbit_mq_container-db618bcd:/var/log/rabbitmq# for x in $(rabbitmqctl list_vhosts | awk '$1 !~ '/Listing'/ { print }') ; do echo "Backed up queues for vhost $x" ; rabbitmqctl list_queues -p $x | awk '$2 > 1 { print }' ; echo " " ; done
Backed up queues for vhost /
Listing queues ...
 
Backed up queues for vhost /ceilometer
Listing queues ...
notifications.sample	212
 
Backed up queues for vhost /cinder
Listing queues ...
 
Backed up queues for vhost /glance
Listing queues ..
 
Backed up queues for vhost /heat
Listing queues ..
 
Backed up queues for vhost /keystone
Listing queues ..
 
Backed up queues for vhost /neutron
Listing queues ..
 
Backed up queues for vhost /nova
Listing queues ..
```

Metrics returned by the rabbitmq_status.py plugin:

```
root@xxxxxx-infra01:/usr/lib/rackspace-monitoring-agent/plugins# ./rabbitmq_status.py -H 172.29.238.65 -n xxxxxx-Infra01_rabbit_mq_container-db618bcd -U maas_user -p xxxxxxxxxxxxxx
status okay
metric rabbitmq_notification_messages int64 0 messages
metric rabbitmq_uptime int64 816711536 ms
metric rabbitmq_messages int64 212 messages
metric rabbitmq_ack int64 5962130 messages
metric rabbitmq_deliver_get int64 5962131 messages
metric rabbitmq_max_channels_per_conn int64 1 channels
metric rabbitmq_deliver int64 5962131 messages
metric rabbitmq_sockets_total int64 58889 fd
metric rabbitmq_publish int64 5854773 messages
metric rabbitmq_fd_used int64 342 fd
metric rabbitmq_mem_used int64 217246960 bytes
metric rabbitmq_fd_total int64 65535 fd
metric rabbitmq_disk_free_alarm_status uint32 1
metric rabbitmq_proc_used int64 4422 processes
metric rabbitmq_mem_limit int64 53976499814 bytes
metric rabbitmq_mem_alarm_status uint32 1
metric rabbitmq_sockets_used int64 321 fd
metric rabbitmq_msgs_excl_notifications int64 212 messages
metric rabbitmq_messages_unacknowledged int64 0 messages
metric rabbitmq_messages_ready int64 212 messages
metric rabbitmq_proc_total int64 1048576 processes
```

##### How can we verify your issue is addressed?
Ensuring the rabbitmq_status.py plugin is properly reporting metrics including the exclusion of the notfication queues.

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?
N/A not a large issue at the moment but it might be as we upgrade customers to Liberty.

##### What branches / milestones do you believe this issue should target?
This is the first time seeing this on 12.x.x environments.  

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1

**Comment by JCallicoat** [comment]
It looks like this is caused by the fact that we switched to vhosts for services in rabbit.

This plugin is now pulling from the default vhost which returns an empty dict.

```
# curl http://maas_user:<redacted>@172.29.238.65:15672/api/queues
[]
```

With the switch using vhosts for services, the plugin needs to poll each vhost (note the / in the vhost needs to be percent-encoded). E.g, /api/queues/%2Fnova.

Additionally, the maas rabbit user needs to be granted permissions to the vhosts.

```
# curl http://maas_user:<redacted>@172.29.238.65:15672/api/queues/%2Fnova
{"error":"not_authorised","reason":"User not authorised to access virtual host"}
```

**Comment by BjoernT** [comment]
@tbyrom138  Do you have MAAS logs from your liberty based tests ?

**Comment by tbyrom138** [comment]
@xeregin  can you help out @BjoernT since you handled that portion of the testing?

**Comment by xeregin** [comment]
There are no available logs for our MaaS tests, unfortunately.

**Comment by git-harry** [comment]
Not tested however this looks like a legitimate issue due to something missed when the repo was updated to Liberty. I think this is a prio-2, there is no simple workaround available however this issue only impact in a failure scenario by reducing the chance of a proactive resolution.

**Comment by JCallicoat** [comment]
I think this is prio-1 because it will result in tons of false alerts as there are usually way more messages in the notifications queues than the threshold to trigger the alert.

**Comment by d34dh0r53** [comment]
Due to this causing an increase in support workload that will most likely mean the disabling of this check I'm setting this at Prio-1.

**Comment by hughsaunders** [comment]
Reproduced, working on a fix.

**Comment by mancdaz** [comment]
```
15:12:14 ********************** Run Holland ***********************
15:12:14 + run_holland
15:12:14 ++ sudo lxc-ls
15:12:14 ++ grep galera
15:12:14 ++ head -n1
15:12:14 + sudo lxc-attach -n jrpcaioiad-d1a_galera_container-26712479 -- /bin/bash -c 'holland bk'
15:12:14 No handlers could be found for logger "holland.core.util.bootstrap"
15:12:14 + HOLLAND_RC=1
```

**Comment by mancdaz** [comment]
@hybridpollo @JCallicoat Whilst there's a valid issue here that is being patched (vhost perms), I do wonder why ceilometer was deployed at all in this environment? The issue above as reported shows notifications that ceilometer itself is generating. None of the other services now generate notifications because we fixed that at root (disabled notifications for all services unless ceilometer was in the environment to consume them).

The presence of ceilometer in the environment suggests something odd.

**Comment by JCallicoat** [comment]
One part of this issue was fixed (adding permissions to the vhosts), but the maas plugin is still only checking the default vhost for notifications.

https://github.com/rcbops/rpc-openstack/blob/master/maas/plugins/rabbitmq_status.py#L31

We have customers paying for professional services to enable ceilometer (and potentially other services), so we will probably see this again in the future. Given what @mancdaz said about notifications being disabled on all the default projects this is probably a much lower priority issue, but should still be fixed as the returned metric does not currently reflect what it is intended to.

**Comment by git-harry** [comment]
@JCallicoat the call to the queues API gives data on all vhosts that the user has permissions for, not just the default.

This first example shows the permissions prior to the fix going in and the data returned by the call to /api/queues. As you can see, the user only has permissions to the default vhost. There are no queues on the default vhost so an empty array is returned.
```
root@master1_rabbit_mq_container-0a18b714:~# rabbitmqctl list_user_permissions maas_user                                                                                                                    Listing permissions for user "maas_user" ...
/       .*      .*      .*
root@master1_rabbit_mq_container-0a18b714:~# curl -H 'Authorization: Basic bWFhc191c2VyOjI4MjNlOWJkMmY2YjZkNzZiZWMwMDQ3YmIyZDEyOTIzNjU4OWRjNWNjNDEwOTAxYTlkYTJjNzVkODU3' http://172.29.239.33:15672/api/queues | python -m json.tool
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100     2  100     2    0     0    415      0 --:--:-- --:--:-- --:--:--   500
[]
```
This second example was done after the fix was applied. Notice that the user maas_user now has permissions to several vhosts and data is being returned for a number of them.
```
root@master1_rabbit_mq_container-0a18b714:~# rabbitmqctl list_user_permissions maas_user
Listing permissions for user "maas_user" ...
/       .*      .*      .*
/cinder .*      .*      .*
/glance .*      .*      .*
/heat   .*      .*      .*
/keystone       .*      .*      .*
/neutron        .*      .*      .*
/nova   .*      .*      .*
root@master1_rabbit_mq_container-0a18b714:~# curl -H 'Authorization: Basic bWFhc191c2VyOjI4MjNlOWJkMmY2YjZkNzZiZWMwMDQ3YmIyZDEyOTIzNjU4OWRjNWNjNDEwOTAxYTlkYTJjNzVkODU3' http://172.29.239.33:15672/api/queues | python -m json.tool | grep vhost | uniq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 83306  100 83306    0     0  2510k      0 --:--:-- --:--:-- --:--:-- 2542k
        "vhost": "/cinder"
        "vhost": "/heat"
        "vhost": "/neutron"
        "vhost": "/nova"
```

**Comment by JCallicoat** [comment]
@git-harry Ah! My bad, carry on!
