### ISSUE TITLE
Constant pip issues on host level due to bad pip links config handing inside pip_lockdown_role

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#1124]
##### What version (commit) do you encounter this issue on?

r12.1.2

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

pip configuration is 100% managed during RPC upgrade, no more stale links

##### What is actually happening?

```
TASK: [rpc_support | Install pccommon pip dependencies] ***********************
failed: [controller2] => (item=python-openstackclient) => {"attempts": 2, "cmd": "/usr/local/bin/pip install --force-reinstall python-openstackclient", "failed": true, "item": "python-openstackclient"}
msg: Task failed as maximum retries was encountered
failed: [controller3] => (item=python-openstackclient) => {"attempts": 2, "cmd": "/usr/local/bin/pip install --force-reinstall python-openstackclient", "failed": true, "item": "python-openstackclient"}
msg: Task failed as maximum retries was encountered
failed: [controller1] => (item=python-openstackclient) => {"attempts": 2, "cmd": "/usr/local/bin/pip install --force-reinstall python-openstackclient", "failed": true, "item": "python-openstackclient"}
msg: Task failed as maximum retries was encountered

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
rpc_support | Add rpc_support key to nova ------------------------------ 10.87s
rpc_support | Check for rpc_support keypair in nova -------------------- 10.84s
rpc_support | Install pccommon pip dependencies ------------------------- 5.83s
rpc_support | Add HWRaid apt keys --------------------------------------- 5.81s
rpc_support | Set history format file ----------------------------------- 1.36s
rpc_support | Host kernel sysctl tuning --------------------------------- 1.35s
rpc_support | Install HWRaid packages ----------------------------------- 0.68s
rpc_support | Install packages required for support --------------------- 0.68s
rpc_support | Install host packages required for support ---------------- 0.67s
rpc_support | Drop rpc-release file ------------------------------------- 0.35s
           to retry, use: --limit @/root/rpc-support.retry

controller1                : ok=24   changed=1    unreachable=0    failed=1
controller2                : ok=24   changed=1    unreachable=0    failed=1
controller3                : ok=24   changed=1    unreachable=0    failed=1
controller3_utility_container-841d3a0b : ok=16   changed=2    unreachable=0    failed=1

Ouch :

root@controller1:/opt/rpc-openstack/rpcd/playbooks 1465320947 # cat ~/.pip/links.d/openstack_release.link
http://172.29.236.10:8181/os-releases/11.2.8/


 cat ~/.pip/pip.conf
[global]
no-index = True
pre = True
timeout = 120
trusted-host =
        172.29.236.10

[install]
upgrade = True
allow_all_external = True
find-links =
        http://172.29.236.10:8181/rpc-releases/r11.1.3/
        http://172.29.236.10:8181/os-releases/11.2.8/

```
##### How can we reproduce this issue?

Running Kilo to Liberty upgrade via upgrade.sh

##### How can we verify your issue is addressed?

pip.conf is 100% of the time correct

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

I have to implement workarounds in maintenance templates

##### What is your evaluation on the importance of this issue, and why?

None of the Liberty upgrades work without manual patches

###### Remove branches (lines) you do not wish to target.
- [x] Master
- [x] liberty-12.2
- [x] liberty-12.1

**Comment by BjoernT** [comment]
Manual workaround:

```
ansible hosts -m file -a 'dest=/root/.pip/pip.conf state=absent'
ansible hosts -m file -a 'dest=/root/.pip/links.d/openstack_release.link state=absent'
ansible hosts -m file -a 'dest=/root/.pip/links.d/rpc_release.link state=absent'
  
 
cat << EOF > /opt/rpc-openstack/openstack-ansible/playbooks/pip-lockdown.yml
---

- name: Dropping pip configuration
  hosts: hosts
  roles:
      - { role: "pip_lock_down" }
EOF
( cd /opt/rpc-openstack/openstack-ansible/playbooks/ && openstack-ansible pip-lockdown.yml )
```

**Comment by git-harry** [comment]
There appears to be two separate issues here:

1. There is an rpc-releases link present. We should be cleaning this up, but I don't remember a task being added to do it. While the link should be removed, its existence should not cause any failure. Pip will grab the latest version meeting its requirements and so the old rpc-releases repo will effectively be ignored. If the repo containers have been rebuild, and so the rpc-releases repo no longer exists, the link will be skipped by pip.
2. The os-releases link still references a Kilo version. This indicates pip_lock_down has not been run with OSA Liberty code on the controller. I'm don't think this would be picked up by our testing because we use AIOs and so the os_nova role is run on the host. Given that r12.1.0 has been through QE and there have already been a number of upgrades done the implication is that this has been introduced by r12.1.2. Reviewing the changes I am unable to find the cause. @odyssey4me what drops pip.conf on the controllers? I am unable to find the relevant code path.

**Comment by odyssey4me** [comment]
@git-harry The pip.conf is generated from various sources using the script at https://github.com/openstack/openstack-ansible/blob/liberty/playbooks/roles/pip_lock_down/files/pip-link-build.py so the removal of the additional link file is one step to resolve this. The pip_lock_down role is activated mostly through role meta dependencies, but sometimes also through the playbooks. We're in the process of consolidating the pip_install and pip_lock_down roles in master so that this whole things is a little more predictable and sensible, but for liberty/mitaka the implementation is as it was in kilo. What's changed here is that RPC-O in Liberty is now using the OSA repo-build process, so the Kilo repo-build process and pip configs need to be cleaned up during the upgrade.

**Comment by git-harry** [comment]
@odyssey4me my question was specifically in regards to pip.conf on the controllers. I can't see anything in OSA that would create that file on a controller, only on the containers on the controllers. If that's the case I'd say that's a bug in OSA because it's unexpected but it might go some way to explaining what is being raised by this issue.

**Comment by BjoernT** [comment]
@git-harry You are right it is usually related to MAAS plays, putting a pip.conf in place

**Comment by odyssey4me** [comment]
@git-harry If by 'controllers' you mean the hosts for the control plane then I understand the question better. The only playbooks I know of that target the control plane hosts are lxc-hosts-setup.yml, lxc-container-create.yml and openstack-hosts-setup.yml. Those playbooks and the roles referenced in them (and their dependent roles) do not place a pip.conf down. The only roles which reference pip at all are py_from_git and lxc_hosts, but none reference or depend on pip_lock_down.

**Comment by git-harry** [comment]
9192f94da6a6f9b916b8ad294eae5a2ae44d261b removed the playbook repo-pip-setup.yml. It seems this was having the side effect of locking down the controller hosts for the OSA repo in addition to adding the RPCO repo required by Kilo.

pip_lock_down does not fully manage the directories it creates under /root/.pip. When we've switched to Liberty the file /root/.pip/links.d/rpc_release.link has been left behind and pip_lock_down does not ensure the directory only contains the files for which it controls the configuration.

The only RPCO playbooks that run pip_lock_down relate to logging which is the penultimate step of deploy.sh, this means that on a greenfield Liberty deployment rpc-support.yml and setup-maas.yml are not using the repo server and on upgrades they are using the Kilo version.

I think we should look to add a playbook to ensure all hosts have the appropriate pip config prior to any RPCO tasks, we should also consider moving https://github.com/rcbops/rpc-openstack/blob/master/scripts/upgrade.sh#L43-L46 into deploy.sh

cc @mancdaz

**Comment by odyssey4me** [comment]
@git-harry Yes, I believe that the way that the pip lock down doesn't manage all the content in ``/root/.pip`` is by design in order to allow a deployer to add additional links files outside of the OSA framework. Personally I think it's confusing and would rather see ``/root/.pip/pip.conf`` simply be managed through the use of a template instead of a bunch of files and a script... but obviously that's not something that helps this particular issue as the issue specifically relates to the Liberty deployment and a design change would not be backported.

**Comment by mancdaz** [comment]
@git-harry I'd agree to the suggested approach, and also think that this should be a prio-1
