### ISSUE TITLE
f5-config.py creates priority groups for repo servers

### ISSUE THREAD

**Issue by Mudpuppy12** [rcbops/rpc-openstack#190]
The current configuration for f5-configy.py scripts creates a pool for the repo servers with a priority group of 100, 95, 90 with a balancing scheme of fastest-node. This forces all the traffic to go through a single node that we discovered. They should be set to all the same priority with least connection node for balancing.

current output

create ltm pool /QE-IAD3-1/QE-1_POOL_REPO { load-balancing-mode fastest-node members replace-all-with { QE-1_NODE_569038-infra03_repo_container-45441f9f:8181 { priority-group 100 } QE-1_NODE_569037-infra02_repo_container-20bae48b:8181 { priority-group 95 } QE-1_NODE_568575-infra01_repo_container-9c514b02:8181 { priority-group 90 } } min-active-members 1 monitor /QE-IAD3-1/QE-1_MON_HTTP_REPO }

something like

create ltm pool /QE-IAD3-1/QE-1_POOL_REPO { load-balancing-mode least-connections-node members replace-all-with { QE-1_NODE_569038-infra03_repo_container-45441f9f:8181 { priority-group 100 } QE-1_NODE_569037-infra02_repo_container-20bae48b:8181 { priority-group 100 } QE-1_NODE_568575-infra01_repo_container-9c514b02:8181 { priority-group 100 } } min-active-members 1 monitor /QE-IAD3-1/QE-1_MON_HTTP_REPO }

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master (https://github.com/rcbops/rpc-openstack/pull/1290)
- [x] mitaka-13.0 (#1322)
- [x] liberty-12.2 (https://github.com/rcbops/rpc-openstack/pull/1337)
- [x] kilo (https://github.com/rcbops/rpc-openstack/pull/1336)

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [ ] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [x] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links:

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [x] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [ ] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by BjoernT** [comment]
Still a valid concern

**Comment by mancdaz** [comment]
@nategraf does this need to be considered for backports? Also, please can you update the description with info about doc impact and release notes etc, and links to the backport PRs once they are made.

**Comment by git-harry** [comment]
Was this tested in a hardware lab? The pull request checks do not test this script. The description above states that additional testing has been included with the change - what is this additional testing?

**Comment by nategraf** [comment]
@mancdaz I couldn't find a place in the docs where the exact load balancing method for repo servers is mentioned. (I could have just missed it) A docs change is not needed for this patch in particular, unless it is decided that all load balancing default configurations should be documented.
@git-harry This has not been tested in the hardware lab. I consulted with Johnny and Edgar on the networking team and both found that the change to be small and said the configuration it produced looked good. The change I made in the PR follows established code paths by simply changing a hard coded setting so there is not a possibility of breaking the code itself. There could be an issue if, for some reason, the repo servers behave poorly in an active-active configuration. To my knowledge this is not an issue because until the repo servers are synced, they are removed from the load balancer, and once they are synced they will serve equivalent packages. Hardware lab testing may be needed, but this I will need to defer to y'all for that, as I no longer have access to any hardware lab resources.

**Comment by b3rnard0** [comment]
@git-harry @mancdaz Please confirm that the backports for Liberty and Kilo are needed.

**Comment by mancdaz** [comment]
Yes, this should be backported to kilo and liberty since the errant behaviour will exist there too.

EDIT: Backports have been submitted and links added to the description

**Comment by Frank-ZhangXin** [comment]
@b3rnard0 looks @mancdaz already has done with backport, though I'm in progress. Avoiding duplicated work, I won't commit from my side.
