### ISSUE TITLE
neutron_linuxbridge_agent_check, nova-compute check execute only once and iterate over hostnames

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#192]
Currently we do see massive burst of alerts in case something is off with the neutron server or any other central service. The issue primarily with the bursts are that we check the neutron agent per compute node instead of executing the check on the infra nodes and iteration over all agents and looking for downed neutron agents with just one api call.
The goal is:
- Remove neutron_linuxbridge_agent_check and nova-compute from all compute nodes
- Add the neutron_linuxbridge_agent_check and nova-compute  to the infra nodes
- Issue one api call (agent-list) and check for all agents which are enabled but not marked as alive

Personally I would just name this check neutral like neutron_agent_alive_check and we just report the dead components in one alert.
This needs to be back ported to Kilo and Juno

**Comment by BjoernT** [comment]
The maas playbooks should remove the neutron linuxbridge agent checks as part of this bug

**Comment by claco** [comment]
So, part of the risk of this is that if you have > 30 computes, we're going to hit the MaaS check metric limits per request. While we could raise a status for all_ok or something like that, this might not work as a replacement for the other thing, which has other metrics..

**Comment by BjoernT** [comment]
I actually would not expose any metric since we check many agents at once. We probably can just expose a binary metric for all linux bridge agents up/down

**Comment by b3rnard0** [comment]
@nrb What's the target milestone for this given that it's got a high priority?

**Comment by nrb** [comment]
This high priority was given with the normal sprint bump.

However, the milestone could probably 11.1.0 or 11.0.1

**Comment by git-harry** [comment]
@prometheanfire I assume you're not working on this? Shall I remove your assignment?

@BjoernT the MaaS checks are designed to be located with the relevant physical host. This request strikes me as being a fundamental design change and breaks the link between entity and alarm. @mancdaz @andymcc do you have any thoughts on this request?

**Comment by BjoernT** [comment]
@git-harry This is exactly the current problem that the check is on the host and when the host is down we won't even know. AFAIK, the check does just a agent-list |grep linux-bridge and looks for the hostname. From the resource perspective is really not smart to call the API over and over again, to check a central agent information. Hence this bug. I would agree to leave it on the host if we would do additional checks on the actual node, but currently this is not the case.

**Comment by git-harry** [comment]
@BjoernT what you're describing there is the issue with host-down alerting, that's not specific to this plugin. I would like to hear other views on this change because there are a number of other plugins that follow this pattern.

**Comment by mancdaz** [comment]
@BjoernT I tend to agree with @git-harry in that the problem of many alerts due to a single system being unavailable is not a problem with the plugins - more a fact that maas does not have good event correlation.
If keystone was unavailable, most checks would fail, but we're also not going to try and work around that in the plugins either.

**Comment by rackertom** [comment]
I think this bug points out several issues with monitoring and alerting that perhaps have not been fully considered. The crux of @BjoernT concern could be summed up by noting we shouldn't introduce undue load on the system we're monitoring with the mechanism used to monitor. I fully agree with this idea- Performing N queries when one would do is a pretty bad design.

On the other hand, we have the common problem introduced in the push vs pull monitoring and metric collection camps. With a pull methodology, detecting host down situations is somewhat simple in that if no response is received the check presumes a host is down. When using a push methodology, though, the collector(s) need to be intelligent enough to know that `N * $period` has passed for an individual check that is supposed to report in `$period` time after which the presumption is made that the host is down.

So, IMO the correct thing to do here would be to collect as much status data in the smallest number of operations. We should also report the status as a per-item status, not as a binary for the collective. The latter has literally no operations use at all except to say that "somewhere there is a problem". So, we may need to know about API limitations when submitting data, but that would be a much easier issue to deal with (I presume) than giving a generic problem alert that only leads an operations member to a wild goose chase attempting to find the origin of the issue.

I'd like to point out that we are stumbling on almost every single common issue anyone that attempts to build their own monitoring and metric collection system has had trouble with. This is a very hard road, and I really think we should have adapted an existing system during the MaaS refactor.

**Comment by git-harry** [comment]
@rackertom I agree that plugin design should consider the load placed on the system. I also agree that duplicating data collection should be avoided where appropriate. What I'm not so sure about is whether that's a fair assessment of the setup with this plugin.

Regarding how status is reported, the status line is mandatory for plugins and is only used to notify if there is a failure collecting the metrics. I think if the plugin gets to the point were a per-metric collection status is deemed necessary the plugin is probably too big. The status error messages are not generic and should give specific information regarding the reason for failure.

Can you give examples of existing systems that you think would have been good candidates for adaptation?

For what you've described, it sounds like you think this plugin should run on one host and collect all the linuxbridge agent metrics. Originally, as @claco pointed out, that would not have been very scalable due to the 30 metric limit, I believe this limit no longer exists in MaaS. If one agent collects all the metrics and that agent goes down, due to the lack of agent-down alerting, there is an unmonitored single point of failure. If there is one alarm to alert on the state of all the linuxbridge agents any failure of other linuxbridge agents on different hosts will generate no new alert. If there is a per-agent-metric alert, that is equivalent to today. If a compute host goes down, currently that would cause no alerting by alarms such as discussed here, but if this type of check was managed centrally there would be a lot of alarms generated against multiple hosts.

While I'm not suggesting the current implementation is perfect there are a number of consequences that flow from switching to the design suggested by this issue and on balance I'm not convinced that an unquantified amount of reduced load or a reduced number of alerts under certain circumstances is an improvement when the trade off will be increased alerting under other circumstances and breaking the link between the metric and the entity.

**Comment by d34dh0r53** [comment]
@tomc603 @git-harry Is this something we can get ironed out by the 14th for `r11.1.1`? Or should I re-prioritize it?

**Comment by tomc603** [comment]
It _sounds_ like we could address some of the issue to an acceptable level without having to boil the ocean first. But I'm not entirely sure what the full scope of the work is here.

**Comment by BjoernT** [comment]
So this is a real issue and I added the nova-compute service as well since it shows the same symptom.
You can't check the nova-compute for one compute node on the same compute node. Whenever this host goes into a awkward state, you won't know that nova-compute is down. Other checks might still work like ping, depending in which state it is.

**Comment by mancdaz** [comment]
@tomc603 did you get any further with this?

**Comment by mancdaz** [comment]
Hi @BjoernT 

Just thinking through the possible implementation here:

The idea would be to not deploy checks per compute node. Instead do single API call and from the controller nodes and iterate through all agents/services for a given project (eg nova or neutron). If all are 'enabled' and 'up' , return a single metric with a value of 1.

The problem in my head comes when there is an issue for one of the services. That single metric would return a fail value of 0, but wouldn't contain any info about which service on which node had failed. The maas system expects configured checks to continue to report the same metrics. 

What we might need to do is to have an 'all_services_are_ok' metric that reported 1 or 0, and then another metric with a string type that contained a string which was a list of all down services on which host.  This string would contain 'no services down' when conditions are good.

This way we only ever have 2 metrics to report. The only downside is if there are a lot of downed services this string might become too long. I can't find the exact character limit for string metric types but it's in the low hundreds.

Thoughts?

**Comment by mancdaz** [comment]
@BjoernT Having discussed the possible implementation with @git-harry and @andymcc, it's worth noting the potential side effects:

- all alerts for any service would now be logged against the infra nodes, not the individual compute node that has the issue
- if a service went down on one compute node, causing an alert for that check, and then another service went down on another node before the first had cleared, you wouldn't receive a separate notification for the second because it is under the same check
- it would be difficult to guarantee that the actual host name of the node that has the issue is included in the alert, if there are many (limitations of the 'string' metric type mentioned above)

Whilst I tend to agree that since all checks are done via the API, we can make a single API call to check all services, I do wonder whether it's worth doing given the loss of granularity you'd get in your alerting.

**Comment by andymcc** [comment]
One addition to that - you won't be able to stop receiving alerts for under-repair devices (e.g. you put compute host x under repair, you will still get the alerts on infra host y, because it isn't under repair), and perhaps worse - vice-versa where you mark the infra host x as under repair/maintenance you will stop receiving alerts from any of the hosts with associated alerts - even if they are legitimate alerts.

**Comment by BjoernT** [comment]
Yes i know it is difficult, but not getting an alarm if nova-compute and the node goes down is also bad. Neither solutions are perfect. Since we implemented a agent down in RPC-Support, outside of the MAAS team, we will utilize this and leave the checks as they are. It seems we get out of this chicken-egg problem only with two checks, nova and agent health. Hopefully agent health checks in MAAS will work this decade ... until then we fix it in RPC with our own tools. So we can close this issue
