### ISSUE TITLE
Documentation does not clearly state how to checkout a branch on the osad submodule

### ISSUE THREAD

**Issue by miguelgrinberg** [rcbops/rpc-openstack#241]
The command:

    git clone —recursive -b kilo https://github.com/rcbops/rpc-openstack.git

sets the kilo branch on rpc-openstack, but not on the osad submodule. We need to document that the submodule needs to be switched to the desired branch as well.

**Comment by miguelgrinberg** [comment]
After some additional investigation, my initial thought that OSAD was pinned to a master sha seems incorrect. There is a lab that ended up with a Liberty release of horizon that made me think the problem was the pinning, but I have been unable to reproduce on my own. We'll redeploy this lab to see if the problem can be reproduced.

**Comment by jpmontez** [comment]
Perhaps, the recursive checkout could remain, but specifying the branch in the same command could be left out. There may be some confusion when a `git branch` is run after the original command is run because you're essentially running within a headless repo.

An alternative could be cloning the entire repo, checking out a specific branch/tag and then running `git submodule update` to ensure the current OSAD SHA is used.

**Comment by git-harry** [comment]
I can't reproduce any issue here. The recursive flag checks out the openstack-ansible repo to the correct SHA. I did find a couple of issues with http://docs.rackspace.com/rpc/api/v11/bk-rpc-installation/content/ch-hosts-deployment.html which describes cloning the repo so I will raise an issue on the rpcdocs repo.
