### ISSUE TITLE
MaaS doesnt appear to look at correct Keystone token key for expiration date

### ISSUE THREAD

**Issue by nrb** [rcbops/rpc-openstack#349]
Running a MaaS check on a lab resulted in the following error:

```
root@578160-infra01:/opt/rpc-openstack/rpcd/playbooks/roles/rpc_maas# python /usr/lib/rackspace-monitoring-agent/plugins/neutron_service_check.py  --host 578162-infra03_neutron_agents_container-c48567ea 172.25.240.49 
status error 'expires_at'
```

```
(Pdb) l
328
329     def is_token_expired(token):
330         import pdb; pdb.set_trace()
331         for fmt in ('%Y-%m-%dT%H:%M:%SZ', '%Y-%m-%dT%H:%M:%S.%fZ'):
332             try:
333  ->             expires = datetime.datetime.strptime(token['expires_at'], fmt)
334                 break
335             except ValueError as e:
336                 pass
337         else:
338             raise e
```

The correct key/value pair appears to be `token['token']['expires']`

**Comment by miguelgrinberg** [comment]
I think this is a keystone v2 vs. v3 token difference. See https://github.com/openstack/keystone/blob/4d2bbe0e7c4e08c372e229f5622b9cfc2c25c3c6/keystone/token/providers/common.py#L47

**Comment by mancdaz** [comment]
This is not the token.  This is the way that maas_common is parsing the auth_ref that we lay down on disk.  The auth ref before an upgrade (generated from a call to keystone api v2) looks different to what we're trying to parse after an upgrade (maas_common now expects to parse an auth_ref generated from a call to api v3).  See:

https://github.com/rcbops/rpc-openstack/issues/321

This should have been fixed in the post upgrade rm of the auth_ref

https://github.com/rcbops/rpc-openstack/pull/327/files

**Comment by nrb** [comment]
Aha, I think I identified what happened.

During the course of our upgrade, we ran `scripts/upgrade.sh`. This errored out in the OSAD `run-upgrade.sh`, with Swift failing to install because of missing Trusty backports.

From there, we continued manually. However, we missed running the rm auth_ref line, so this was user error, not a code bug.

**Comment by nrb** [comment]
Closing this for now, as it was user error.
