### ISSUE TITLE
rpc-release file shows incorrect DISTRIB_RELEASE value after Juno->Kilo upgrade

### ISSUE THREAD

**Issue by toxick** [rcbops/rpc-openstack#533]
I just (ostensibly) completed the Juno->Kilo upgrade in a lab, and found that the DISTRIB_RELEASE value has not been updated in the rpc-release file:

  656  2015-10-28 18:05:42  git clone -b r11.0.3 --recursive  https://github.com/rcbops/rpc-openstack /opt/rpc-openstack

root@<host>:~# cat /etc/rpc-release 
DISTRIB_ID="RPC"
DISTRIB_RELEASE="10.1.15"
DISTRIB_CODENAME="wee-5ive"
DISTRIB_DESCRIPTION="Rackspace Private Cloud"

**Comment by d34dh0r53** [comment]
This should be resolved

**Comment by byronmccollum** [comment]
@toxick Was this a clean upgrade all the way through, or did you encounter any failures along the way...? There is a scenario where I can see this happening, which involves a potentially misleading "what to do next" message in the event of a failure, leaving the cluster in a partially upgraded state.

Upgrading from Juno -> Kilo via RPC's `upgrade.sh` is a 2 step process:

First the [OSA bits get upgraded](https://github.com/rcbops/rpc-openstack/blob/kilo/scripts/upgrade.sh#L39) via OSA's `run-upgrade-old.sh`, then the [RPC bits get upgraded](https://github.com/rcbops/rpc-openstack/blob/kilo/scripts/upgrade.sh#L47) via RPC's `deploy.sh`.

If there is a failure upgrading the OSA bits, `run-upgrade-old.sh` informs you to manually re-run the failed playbook, plus any remaining playbooks. If you did re-run these playbooks, but stopped there, you would have a partially upgraded cluster. The OSA bits would be running Kilo, but the RPC bits would still be running Juno. And that's where it's misleading, because that's not the end of the upgrade. You also need to manually run the [rest of what's in RPC's `upgrade.sh`](https://github.com/rcbops/rpc-openstack/blob/kilo/scripts/upgrade.sh#L42-L51).

If you still have access to this environment, can you check the contents of both `/etc/rpc-release` and `/etc/openstack-release`. I have a feeling OSA will say Kilo, and RPC will say Juno.

**Comment by byronmccollum** [comment]
Unless you've run `deploy.sh` in the mean time...in which case the RPC bits would have been upgraded, and `rpc-release` would reflect the correct version.

**Comment by toxick** [comment]
rpc-release shows juno, openstack-release shows kilo, as you expected.  Will run through the "rest of what's in RPC's upgrade.sh." and update the maintenance template.

**Comment by BjoernT** [comment]
This issue seem to come up when the upgrade or install stalls before the rpc-support.yml playbook runs.
Since the OSA upgrade.sh script will cover olny OSA playbooks when aborting, admins would have to manually resume rpc-openstack/deploy.sh and picking up all playbooks manually which are executed after the OSA upgrade.sh. Running manually the rpc-support.yml playbook will update the rpc-release file

**Comment by toxick** [comment]
After running upgrade.sh manually, rpc-release shows DISTRIB_RELEASE="r11.0.1", which is better, but still not the version I checked out (r11.0.3).  Is this expected?

root@host:/opt/rpc-openstack# git describe --tags
r11.0.3

root@host:/opt/rpc-openstack# grep -r "r11.0.1" .
./rpcd/playbooks/group_vars/all.yml:rpc_release: r11.0.1

**Comment by BjoernT** [comment]
Yeah we have to update https://github.com/rcbops/rpc-openstack/blob/kilo/rpcd/playbooks/group_vars/all.yml#L19 every time we cut a release. Unfortunately we are cutting r11.0 and r.11.1 out of the same stable branch so this file needs to be altered before every tag....  so home made problems here......

**Comment by byronmccollum** [comment]
The rpc_release variable was accidentally not bumped for r11.0.2 and r11.0.3 tags.

**Comment by git-harry** [comment]
Maybe we should just get git to tell use the tag instead of manually updating this e.g. 'git describe --all'

**Comment by byronmccollum** [comment]
Just not to lose sight...there are two issues described here:

1. The `rpc_release` variable doesn't get updated when new tags are cut. This should be address by #673.

2. Partial Juno -> Kilo upgrade, where an OSA upgrade step fails, and only informs you to finish running the OSA playbooks, leaving the RPC playbooks unrun, and therefore the `rpc-release` file never being updated. This still needs addressing in some manner.

**Comment by mancdaz** [comment]
@byronmccollum I think [this issue](https://github.com/rcbops/rpc-openstack/issues/324) (never resolved) covers your second point ?

**Comment by byronmccollum** [comment]
@mancdaz...Yeah, it does!

**Comment by d34dh0r53** [comment]
:+1:

**Comment by mancdaz** [comment]
This can be closed. It's a dup of the referenced issue above. That one needs to be addressed though. @d34dh0r53

**Comment by nrb** [comment]
@mancdaz Point 1 from Byron still needs 'fixed', which is in #673. That may not be vital, but would be appreciated.
