### ISSUE TITLE
Maas: memcached check enforces exact patch level 

### ISSUE THREAD

**Issue by stevelle** [rcbops/rpc-openstack#603]
should add either a less-strict-mode argument or just loosen checking to minor version number

**Comment by sigmavirus24** [comment]
`--service` as an option name doesn't intuitively make sense to me. I know it's longer bug `--disable-version-check` is a better option name if we want to turn off the version check altogether as an option.

I'm okay having a list of VERSIONS that we know the software works with and check explicitly for each of them. We should re-evaluate the versions, however, each time we cut a new release (r11, r12, etc.)

**Comment by stevelle** [comment]
I don't know if I made this clear by my proposed --service arg was meant to flag a specific version string as allowed: e.g. python memcachhed_status.py --service "1.4.15" 172.29.238.249

--service-version would work as well.

we could also --disable-version-check and disable the check, but that is like driving with headlights off, and I didn't want to make that the only option.

**Comment by stevelle** [comment]
paging input from @git-harry as well, as someone who pays attention to maas checks and might have a different perspective on the fix.

This is something that is important for reuse of our check plugins by the RPC-R team for their up-coming soft launch.  The RHEL memcached package is used for OSP is 1.4.15 which causes this check to immediately fail.  When their engineers patch the check file to allow the 1.4.15 memcached service version instead, the checks work fine.

**Comment by git-harry** [comment]
@stevelle, the use of an argument to specify the expected version moves the responsibility for validating a version works with the plugin from the plugin maintainer to the plugin consumer. For rpc-openstack I'm not sure that provides any benefit but for other users, assuming the new version works, I can see how that might be useful because verifying versions not used by rpc-openstack is always likely to be a low priority. I think it would need to include the appropriate warning so that users don't just bump the version without checking the output is consistent.

**Comment by robb-romans** [comment]
The --version or -v flags almost always imply the incantation will simply return the version of the command itself. Using those as you intend would be confusing to me, at least.

**Comment by sigmavirus24** [comment]
I'm increasingly in favor of keeping a list (or set) of versions that we know work and are good and making sure we update them each time we release a version that is on a new supported platform. It's the simplest solution. It ensures it only works on things we've tested rather than whatever the user feels like telling us is there. It's a far less disruptive change as well. (Incantation of the plugin, etc. do not change as a result or diverge based on product these plugins are deployed with.)

**Comment by stevelle** [comment]
I'm decreasingly interested in discussing a solution (yes, it has been less than 24h). I think we have two decent candidate solutions with little technical barrier but significant philosophical differences. I see strengths to both.

FWIW - The reason I didn't propose --version initially was as @robb-romans states but there is already somewhere else in the plugins where we overload --version so it wouldn't be out of left field, but it wouldn't be good either.

**Comment by stevelle** [comment]
Fix is proposed, based on the principle of listen to the person who feels the strongest about a particular solution.
