### ISSUE TITLE
role_path should include /etc/ansible/roles

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#659]
OSA is starting to import external roles and put them in /etc/ansible/roles, so that should be in the search path.

**Comment by odyssey4me** [comment]
There is no need to do this because I'm pretty sure that Ansible does this by default. It first checks where you specify a path in ansible.cfg, then it checks for a configured env var, then it checks /etc/ansible/roles/. Essentially it uses each configured location as a search path.

See the defaults here: https://github.com/ansible/ansible/blob/devel/lib/ansible/constants.py#L129

**Comment by odyssey4me** [comment]
@hughsaunders I take this back. It seems, from my testing, that the entry in ansible.cfg replaces the default. So the search path that ansible takes is:

```
<current directory> / roles / <role name>
<current directory> / <role name>
<roles_path value from ansible.cfg> OR <default roles path, ie /etc/ansible/roles>
