### ISSUE TITLE
Deploy.sh has duplicated code as it doesn't use OSA/run-playbooks

### ISSUE THREAD

**Issue by hughsaunders** [rcbops/rpc-openstack#691]
For example the code to add iptables rules for instance access to neutron metadata in AIOs. 

We may be able to reduce duplication by utilising OSA/run-playbooks in RPC/deploy.

**Comment by nrb** [comment]
I'm not sure we want to use `run-playbooks.sh`, since it's pretty much a dev tool. Also, `run-playbooks.sh` historically ran playbooks in a different order than the `setup-everything.yml` playbook.

I almost think Harry's issue #701 makes sense if we want to separate out the logic so AIO and dev specific code isn't pulled in. However, having shared install logic is useful so we can be assured code paths that are tested in AIOs are actually what gets deployed...

**Comment by prometheanfire** [comment]
The associated PR for this was closed, I'm not sure this still needs to be around, leaving a note here that we will close this on the next bug triage.

**Comment by cloudnull** [comment]
This seems to be forgotten, closing now. If this needs to be re-opened in the future please feel free to do so.
