### ISSUE TITLE
switch config_drive_format default to vfat

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#783]
this will allow us to do migrations

https://github.com/openstack/nova/blob/master/nova/virt/libvirt/driver.py#L6350-L6364

**Comment by git-harry** [comment]
I've removed the milestone because, to my knowledge, this not been planned to be part of the release.

**Comment by b3rnard0** [comment]
This was added a while back for consideration into 13.0. It's likely a candidate to be discussed for consideration in 13.2.

**Comment by prometheanfire** [comment]
I wonder what our efficiency is on working on this (a one line change)

**Comment by git-harry** [comment]
@prometheanfire the reason I've changed this is because I'm attempting to tidy up the issues in the repo. It may feel like things are going backwards but what we're hopefully achieving here is drawing a line in the sand so that going forward we are more efficient and predictable with better tracking of what is being added to the product.

This change seems to be for enabling live migrations, that is relatively significant in function and it strikes me as appropriate to have testing in place for it. What I've done is reclassify this as a medium enhancement and move it to u-suk-dev so that we can make sure it is properly tracked.
