### ISSUE TITLE
Use virtual environments for MaaS plugins and their dependencies

### ISSUE THREAD

**Issue by prometheanfire** [rcbops/rpc-openstack#787]
This will allow us to control what libraries are available to maas to ensure it doesn't get broken by dependency conflicts.

Tasks:

- [x] Reproduce the issue. (N/A)
- [x] Create a PR for fix and/or docs.
- [ ] Incorporate feedback from pull request reviews.
- [x]  What is the gating for this on DEV and/or QE? Add related gating if appropriate. Also make sure current gating passes with this fix.
- [ ] Reach out to reporter to determine if the fix is resolving the issue.
- [x] What are the upgrade impacts (if any).
- [ ] What are the backports are needed (if any).

**Comment by b3rnard0** [comment]
@sigmavirus24 To provide some more information to the onboarding team.

**Comment by git-harry** [comment]
Monitoring docs regarding plugins https://developer.rackspace.com/docs/rackspace-monitoring/v1/developer-guide/#agent-plugin

**Comment by sigmavirus24** [comment]
Since some of our newer hires are picking this up there's some context you'll need:

**Context**

A *virtualenv* is an isolated environment for Python where globally installed dependencies are unavailable (usually) and where you can install dependencies without them conflicting with the global environment or another virtualenv.

**What do we do now and what needs to change**

Presently we install our MaaS *plugins* into a directory and their dependencies into the system (global) environment. What we want is to install our plugins and their dependencies into a virtualenv so we do not install their dependencies globally.

Rackspace Monitoring Agent, as we configure it, uses files that we template into place to run our plugins and generate alarms. Those templates will need to be updated to use the plugins along the lines of:

```
/path/to/maas-plugins-virtualenv/python /path/to/directory-of-plugins/plugin.py
```

This will ensure that the dependencies installed in that virtualenv will be available to plugin.py.

This work will require three parts:

- Creating the virtualenv for our plugins and installing the dependencies there
- Updating the check templates
- Testing that MaaS continues to work

Y'all should get bonus points if you can figure out if you're upgrading a system and attempt to uninstall the old globally installed dependencies. ;) But that's really something else.

Hopefully this explains the task at hand better, so I'm removing `status-needs-information` and unsubscribing from this. If you have more questions, feel free to re-add the label and ping me directly on the issue with those questions.

**Comment by prometheanfire** [comment]
It was suggested that we could just write a wrapper script that sources the virtualenv before running the plugin.  The maas executable itself is independent of system python on linux, so we should be good there.

The issues we are having are due to our use of plugins that can potentially conflict with system packages.

**Comment by alextricity25** [comment]
@sigmavirus24 Are you talking about these templates here:
https://github.com/rcbops/rpc-openstack/blob/master/rpcd/playbooks/roles/rpc_maas/templates/cinder_api_local_check.yaml.j2#L7

**Comment by sigmavirus24** [comment]
@alextricity25 yes. I see the problem with that.

We may need to template the scripts then to have a shebang that points to the virtualenv's python, e.g.,

```py
#!{{ maas_virtualenv_python }}

...
```

And then set that var to the final path to python, e.g., `/openstack/venvs/maas/bin/python` which would work just as well.

**Comment by git-harry** [comment]
Templating the plugins may affect how they are consumed by RPCR

**Comment by alextricity25** [comment]
@git-harry Can't we just drop the rendered files in the same location they are dropped now? I'm not sure how that would affect how they are consumed.

**Comment by sigmavirus24** [comment]
@alextricity25 RPC-R copies the plugins out of our tree for use in their MaaS integration.

**Comment by alextricity25** [comment]
@sigmavirus24  Well..hmm..that's a problem. :) I guess it wouldn't be so easy to template them unless we maintained both the un-templated plugins and the templated ones.

Or we could try what @prometheanfire said and just create a wrapper script that sources the virtual environment before running the plugins

**Comment by git-harry** [comment]
I wrapper script sounds like a reasonable approach to me. I would likely be simple to implement with a single template that iterates over all the plugins.

**Comment by sigmavirus24** [comment]
The wrapper script sounds like indirection that will make debugging maas plugin failures more painful for support. We'd have to document that clearly for them as a breaking change.

**Comment by git-harry** [comment]
Yes, the wrapper script method would need testing to see what impact it has in terms of logging, manual debugging etc but in principle it's only going to be something along the lines of:

```
#! /usr/bin/env bash
/path/to/env/usr/bin/python plugin.py "$@"
```

I might be missing something obvious but that doesn't look like it would be too much of an issue.

**Comment by sigmavirus24** [comment]
@BjoernT @pmesserli (and whomever else you want to rope in from support) would a wrapper script be acceptable for a 13.x virtualenv approach to MaaS plugins?

**Comment by BjoernT** [comment]
Sure why not. As long as the MAAS plugins work we can adapt to anything

**Comment by alextricity25** [comment]
@sigmavirus24 @git-harry @Frank-ZhangXin @cloader89 @ameserole @nategraf 
Something we need to consider is upgrade impacts, and how upgrades would be handled when someone makes the change from an environment that doesn't have the maas plugins installed in a venv, to this new mitaka environment that does.
Although I realize that after an upgrade the binaries will be installed and run in a virtualenv, what about the binaries that have already been installed on the global environment? Do they need to be purged?

**Comment by sigmavirus24** [comment]
So, I think our ideal would be to provide a separate playbook to do that clean up. Let me explain why:

1. OSA does not do clean up for upgrades from pre-venv environments to venv environments (which is the default for the upgrade between certain versions)

1. Support may or may not use MaaS in a venv. We're giving them the option but often times they ask for something, we deliver it, and they decide to not use it without telling us. Auto-cleaning things up after the fact may do unexpected things for them.

1. Having a separate playbook they run means that they can do the clean-up whenever they want. In that case, if a maintenance runs over for a customer, they can log in again after the fact and run the clean-up step(s).
