### ISSUE TITLE
Both OSA and RPC have a user_variables.yml file

### ISSUE THREAD

**Issue by jacobwagner** [rcbops/rpc-openstack#857]
So when deploying RPC you are required to copy both OSA's user_variables.yml file and RPC's user_variables.yml. This can cause issues when trying to figure out what variables from each file are needed / not needed and when recursively copying them to the /etc/openstack_deploy directory. I think we could possible rename the RPC user_variable file to rpc_user_variables.yml.

**Comment by byronmccollum** [comment]
Use `update-yaml.py` to merge the var files. Here are the steps I use...

```
cp -R /opt/rpc-openstack/openstack-ansible/etc/openstack_deploy /etc
cp /opt/rpc-openstack/rpcd/etc/openstack_deploy/user_extras_*.yml /etc/openstack_deploy 
cp /opt/rpc-openstack/rpcd/etc/openstack_deploy/env.d/* /etc/openstack_deploy/env.d

cd /opt/rpc-openstack
scripts/update-yaml.py /etc/openstack_deploy/user_variables.yml rpcd/etc/openstack_deploy/user_variables.yml 
```

**Comment by nrb** [comment]
See also the discussion at #768, where a similar topic has come up.

However, what Byron said is true - the `update-yaml.py` script is meant to merge the two files and result in just one.

How is your automation deploying? Does it need to be updated to use `update-yaml.py` perhaps?

**Comment by jacobwagner** [comment]
Currently our automation does not use the update-yaml.py script as we simply copy all files needed into the correct directory. I will look at what it takes to update our automation.

Thanks

**Comment by prometheanfire** [comment]
Let's not use OSA's user_variables at all, OSA has it because it needs it to gate and it is tuned for that.  If there is anything we need to take we should take that and put it in a file named user_rpc_variables.yml or something.  Support/deployers could then put their stuff into user_support_variables.yml  Then they are totally separate files, we would be only managing our file.  Upstream OSA would need to sort their find output so that support takes precedence though, but that's 'simple'.

**Comment by byronmccollum** [comment]
@prometheanfire Are you suggesting the current `user_variables.yml` in OSA be renamed to `user_variables.yml.aio` because it is specific to AIO configs, and thus gating. Then just add `user_variables.yml.aio` to the list of files that are dropping into etc for AIO / gate builds...?

And for all other scenarios, OSA should ship an effectively empty (or absent) `user_variables.yml`, because...

1. The existing `user_variables.yml` is AIO / gate specific
2. Any values defined in `user_variables.yml` should in fact be role defaults

Yes? No? Maybe? It's complicated?

**Comment by d34dh0r53** [comment]
I think more of what he is saying is that we maintain our own `user_variables.yml` and only use that, we should probably maintain our own `etc/openstack_deploy` directory and not use the OSA one at all.  We're already maintaining that directory, we should have everything we need for a deployment in there and not worry about the error prone merging of files with `update-yaml.py`.  I think this is something to consider for the Mitaka timeframe.

**Comment by prometheanfire** [comment]
Had a reply, but ya, what @d34dh0r53 said.  Also, having a file that we maintain and one specificly for overrides from deployers/support would help.  We would unconditionally overwrite ours while leaving supports alone.  No need for update-yaml at all then.

**Comment by nrb** [comment]
> Let's not use OSA's user_variables at all, OSA has it because it needs it to gate and it is tuned for that.

I think you mean the AIO file, not `user_variables.yml` in general, right? `user_variables.yml` in general is definitely useful outside of gating.

> Upstream OSA would need to sort their find output so that support takes precedence though, but that's 'simple'.

I'm not sure that's a reasonable request of OSA at this point - that's ultra specific to our case, and may not be applicable beyond that. Put another way - I don't disagree that the precedence and overriding mechanism needs revisiting, but asking for that literal filename and precedence is perhaps too specific.

**Comment by byronmccollum** [comment]
So...

1. Ignore OSA's `user_variables.yml` completely
2. Drop in RPC's `user_variables.yml`, containing the entire desired set of defaults for RPC
3. Provide another `foo_variables.yml` file for support to override and / or augment RPC's defaults

Nice clean separation...

**Comment by prometheanfire** [comment]
@nrb upstream OSA already searches for user_*.yml, but doesn't sort that to make sure any type of precedence is maintained, I just want that sort so things are deterministic.

@byronmccollum it'd go more like this, 1 and 2 are the same, 3 is named differently.

3. Provide another `user_foo_variables.yml` file for support to override and / or augment RPC's defaults.

**Comment by byronmccollum** [comment]
Yup.

**Comment by prometheanfire** [comment]
actually, looks like it is not using find, but ls.  so sorting is good

https://github.com/openstack/openstack-ansible/blob/master/scripts/bootstrap-ansible.sh#L121

**Comment by byronmccollum** [comment]
Maybe something indicating the order being sourced, so something like such...

1. `user_01_rpc_variables.yml`
2. `user_02_environment_variables.yml`

Then deployers could break out their vars into logical groups, and control the source order...

1. `user_01_rpc_variables.yml`
2. `user_02_glance_variables.yml`
3. `user_03_nova_variables.yml`

...etc...

**Comment by nrb** [comment]
> actually, looks like it is not using find, but ls.

Yeah, it's already in alphanumeric order per ls.

**Comment by byronmccollum** [comment]
Thinking about this...RPC could then ship a "user_xx_ceph_variables.yml`, that has all the appropriate bits flipped to enable Ceph support in the various services.

**Comment by prometheanfire** [comment]
yep, that'd work

**Comment by prometheanfire** [comment]
we'd probably try to limit rpc-o setting stuff to user_00_whatever.yml though, to let deployers do everything else

**Comment by nrb** [comment]
The original goal was to make sure that we only maintained the differences between RPC and OSA's files, rather than the whole thing. It looks like that wasn't well communicated or implemented.

However, it's probably better for OSA to just move any of those things that must be in `user_variables.yml` into the defaults for the roles. I'm not sure how many, if any, of those exist. A file being required for AIOs/gates makes sense, though.

@byronmccollum Correct; my original attempt at merging things was to break out variables into individual files, but it was shot down by reviewers because some files, at the time, only had 1 or 2 variables.

@prometheanfire That's what user_extra_variables.yml was for originally; it's really just a different name. with numbering at that point.

**Comment by byronmccollum** [comment]
Ship in a sense that it's in tree...with the install guide saying like "move this file to /etc/openstack_deploy to enable X feature"...

**Comment by prometheanfire** [comment]
I don't think the cost of managing it ourselves is that high, there are not that many things listed in OSA at this point.  The cost is low and reward high in my opinion.

I'd rather just have a single rpc-o variables file `user_00_rpc_variables.yml` or something unless there's a good reason for having another file (ceph might be a reason).  The naming means little to me, but having an explicit precedence order would be nice.

**Comment by d34dh0r53** [comment]
This may need it's own meeting

**Comment by odyssey4me** [comment]
To clear up a few misconceptions, I thought I'd add some input here.

OSA should, in an ideal world, deploy a functional environment without any content in user_variables.yml. The functional environment would result in glance using a file back-end, not swift - although we could adjust group_vars to detect whether there is swift in the environment and mke that a sensible default back-end for the glance store, but that's not in place today.

The AIO does not use the etc/openstack_deploy/user_variable.yml at all. It instead uses its own cut-down user_variables from the bootstrap template which is geared specifically at minimising resource usage and setting changes to suit the AIO test case (eg: setting the glance_store back-end to swift).

**The intent of the content in user_variables.yml is simply to provide deployers a 'short cut' to changing common overrides.**

As such this means that rpc-openstack should probably not use etc/openstack_deploy/user_variable.yml at all and should provide content that matters to an RPC deployer for RPC's use-cases.

It is my intent to reduce the number of settings in etc/openstack_deploy/user_variable.yml to nothing more than example content, if that. The side-effect of having all the content in there right now is that it becomes yet another place where documentation is held and gets out of date. It's also created some bad habits where this has become the place where some defaults that roles or the deployment depend on are being set. This needs to stop.

If anyone wants to try out the test case of implementing OSA without content in a multi-node environment and see what blows up and needs fixing, I'd be very supportive of this initiative.

**Comment by nrb** [comment]
> I would expect that ideally RPC's user_variables.yml file should only contain the 'short cuts' that matter to RPC's deployment teams and any overrides of defaults set in OSA that RPC chooses not to use (eg: OSA uses fernet tokens for keystone, RPC chooses not to for a cycle).

I'm pretty sure that is what's there now, looking at the file (https://github.com/rcbops/rpc-openstack/blob/master/rpcd/etc/openstack_deploy/user_variables.yml). Whether or not everyone agrees with all those overrides is another matter, but everything in there is for RPC in one way or another.

> It's also created some bad habits where this has become the place where some defaults that roles or the deployment depend on are being set. This needs to stop.

I'm not sure I've actually seen that, but would agree it's bad practice.

**Comment by odyssey4me** [comment]
FYI https://review.openstack.org/290447 is proposed to master for Mitaka which makes it clear what the file is for.

**Comment by prometheanfire** [comment]
We have multiple issues here, but it mainly boils down to two, ownership and precedence.

## ownership
Files deployed by OSA should be either fully overridden/removed or kept as is.  If the deployer changes the file those changes are overridden.
Files deployed by RPC-O will fully managed by RPC-O.  If the deployer changes the file those changes are overridden.
Files set aside for the deployer are not touched by RPC-O or OSA.

## precedence
`user_*.yml` files are loaded alphanumericly, meaning there is a precedence already defined.

## How do we put these together?
* We (RPC-O) control what files are laid down
* We (RPC-O) can define our own structure
* OSA does not use or suggest to use its `user_variables.yml` `user_secrets.yml` or `user_extra_variables.yml` for deployments.
  * this means OSA doesn't manage any `user_*.yml` file.
* RPC-O will put all RPC-O managed variables into files prefixed with  `user_00_`
  * this could mean we either user one file for all variables (OSA and RPC-O both) or multiple files.
* Deployers would then be free to organize any overrides they need into `user_*.yml` with the suggestion of starting with the prefix `user_01_`
  * these files would exist outside the git trees managed by OSA and RPC-O

**Comment by prometheanfire** [comment]
I'm going to remove myself from this because we are starting to bikeshed over it too much.  OSA exists to be consumed by other projects, in our case RPC.  This means we get to define things to some extent.  We should not be afraid of using the tooling OSA provides to do what we need.  If the previous convention was to do things the wrong way then the previous convention is wrong and should be changed.

**Comment by odyssey4me** [comment]
I'm still confused.

OSA does not lay down the user_variables.yml file. The deployer does. RPC is the deployer.

The use of the user_variables.yml file is heavily referenced in OSA documentation. Using this file for overrides is a great way to make the OSA documentation usable for RPC deployments. If you change that convention, you have to manage the confusion that will come with it.

I still don't really understand where the problem actually is. Is it difficult adding in overrides to the existing user_variables.yml file? Is there some sort of difficulty keeping it up to date somehow?

**Comment by prometheanfire** [comment]
I know OSA doesn't lay that down, I was just being explicit in saying so.

The problem with using user_variables is that in the precedence imposed by OSA it would be fairly high, deployers wishing to override it would have to manage a file named `user_zzz_foo.yml` or something to do overrides.

The issue is as follows.

If we lay down a file, and that file is change we then don't know what do do when updating.  Do we try to keep the changes as we are doing now or ignore the changes and overwrite the file?  By having a separate file and clear order of precedence we can know clearly who manages what and what overrides what.

The devs are not the deployer, support is.  The devs do not do deployments of customer environments, I've done that and it doesn't work at scale.  The roles in this relationship are `OSA` `RPC-O` and `deployer`, each one downstream of the previous.

**Comment by odyssey4me** [comment]
So the issue is that RPC-O developer want to set overrides that it does not want RPC-O support to change? RPC-O developers want to ensure that the file is never changed and that any overrides specified there take the highest precedence?

**Comment by prometheanfire** [comment]
No, the issue is that RPC-O wants to override OSA, deployers should always be able to override both OSA and RPC-O.

There should be at least three layers to the precedence
* OSA being the lowest, setting defaults for OSA in general.
* RPC-O being in the middle, setting defaults useful for RPC in particular
* deployers being the top, setting variables needed for a particular deployment.

**Comment by odyssey4me** [comment]
OSA sets defaults in group_vars and role defaults. This is already the lowest precedence. Nothing needs to change here.

RPC-O already implements a user_variables.yml file which sets defaults useful to RPC in particular.

Deployers of RPC-O change those defaults if they wish to as needed for a deployment.

Any existing overrides set in user_variables.yml should only ever be changed by a major upgrade script, that only ever changes the name - not the value. If there's a new recommended default by RPC-O developers then this should be noted in documentation and support can implement that change as needed.

I really don't think that there should be any merge of repo defaults over the top of user configuration. That is a quick way to make a bad day. Deployers configure their stuff in user space with purpose.

**Comment by prometheanfire** [comment]
> OSA sets defaults in group_vars and role defaults. This is already the lowest precedence. Nothing needs to change here.

yes, I was being explicit here because I don't want any confusion

> RPC-O already implements a user_variables.yml file which sets defaults useful to RPC in particular.

> Deployers of RPC-O change those defaults if they wish to as needed for a deployment.

This means that that file is now unmanaged any future changes would have to be handled by the deployers.  This is a cost they will have for the future of that file.

> Any existing overrides set in user_variables.yml should only ever be changed by a major upgrade script, that only ever changes the name - not the value. If there's a new recommended default by RPC-O developers then this should be noted in documentation and support can implement that change as needed.

That is now how things are done now

> I really don't think that there should be any merge of repo defaults over the top of user configuration. That is a quick way to make a bad day. Deployers configure their stuff in user space with purpose.

that is your opinion, I think we also need supports input on the other option

**Comment by git-harry** [comment]
Work to change the use of variable files has been tracked by https://github.com/rcbops/u-suk-dev/issues/185 and so I believe this issue is no longer required.
