### ISSUE TITLE
Install MAAS remote checks onto the LB device again

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#931]
##### What version (commit) do you encounter this issue on?

r11.1.x

##### What type of issue is this (bug, feature, documentation, regression)?

feature

##### What is the expected behavior?

The MAAS remote checks should be associated and installed onto the LB devices
like it was prior to r11.1.x 
Additionally maas_scheme should be changed to https.

##### What is actually happening?

The MAAS remote checks are now installed onto all infra nodes but only one set is active.
That alone causes confusion and on top of that, the checks are associated to the wrong device since we want to check the F5/Load balancing component not so much the API.

Apart from that there is the real chance that in case of a infra node issue, that people do not enable 
the passive remote MAAS checks anymore and we suddenly have a coverage hole for as long as the infra node is down. Not nice..

##### How can we reproduce this issue?

Should be obvious what the issue is.

##### How can we verify your issue is addressed?

Logging into the montoring.rackspace.com portal and search for all remote checks.
If those checks are assigned to a infra node, this is not the expected behavior.
If checks are assigned to the F5/Load Balancer, it's OK

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Normal prio issue, no workaround present

##### What is your evaluation on the importance of this issue, and why?

See above

##### What branches / milestones do you believe this issue should target?
The list below is what is currently supported for backports, remove branches you do not wish to target.
- [ ] Master
- [ ] liberty-12.0
- [ ] kilo

**Comment by andymcc** [comment]
We currently use config based checks (in the conf.d directory for maas), this allows us to template out and create yaml files to create monitors. This is good for a few reasons:

* Its quicker - we don't have to find out what monitors exist (MaaS server side) and we don't have to interact with the API.
* We can create/edit/delete monitors via templating in ansible - which we couldn't do at all before, it was a fire and forget, and any edits would have to happen manually.

The challenge exists with LB monitors because we can't create conf.d entries on the load balancer itself. This left us with a few options, but in the end after consulting with support, we ended up going with creating the LB monitors on each host, but setting 2 to disabled (so that 3 alerts aren't generated). This would mean in a maintenance state, where the primary infra host is down, a var could be set (lb_check_on_single_host) to adjust the hosts that the LB monitors are setup against.

When lb_check_on_single_host is set to False the monitors will get setup against each host - this prevents a situation where the LB should be working, and VIPs should be fine, but the server MaaS is setup against is under maintenance - suppressing alerts.

The benefit is that we can template ALL monitors/alarms in the same way (using ansible templates and conf.d style entries - which are simpler to manage, setup, diagnose and investigate) - as opposed to setting up the LB monitors in the old way which would mean no edits/deletes/control really.

Hope that explains the situation.

**Comment by BjoernT** [comment]
Yes we perfectly know why the change has been made and it is overall very good.
But we never had a problem with the remote lb_ maas checks, since those were limited to 13 API checks, the speed is not our concern. I would be more OK if maas would understand dependencies so that we could have all remote checks active on all nodes but it does not.

**Comment by git-harry** [comment]
If this work is to be revisited, I think it's appropriate that it is done as part of a minor release. This was changed based on collaboration done with relevant stakeholders however that does not appear to have been sufficient to put this issue to rest and so we need to make sure any further work is including all the relevant people.

I will close this issue in favour of https://github.com/rcbops/u-suk-dev/issues/243
