### ISSUE TITLE
MAAS playbooks use different type of hostnames

### ISSUE THREAD

**Issue by BjoernT** [rcbops/rpc-openstack#941]
##### What version (commit) do you encounter this issue on?

r11.0.0

##### What type of issue is this (bug, feature, documentation, regression)?

Bug

##### What is the expected behavior?

All maas related playbooks should use one type of hostname, either inventory_hostname or ansible_hostname to prevent situations that the host has a FQDN but is only known with a short name in the inventory. That leads to issues that the the verify-maas.yml playbook looks up checks with a different hostname than the checks got created with

For example :
```
root@bjoern-aio3:/opt/rpc-openstack/rpcd/playbooks# grep hostname roles/rpc_maas/templates/nova_api_local_check.yaml.j2
label: "nova_api_local_check--{{ ansible_hostname }}"
        label                   : nova_api_local_status--{{ ansible_hostname }}
		
		
root@bjoern-aio3:/opt/rpc-openstack/rpcd/playbooks# grep hostname verify-maas.yml -B1
        {{ maas_rpc_scripts_dir }}/rpc-maas-tool.py verify-created
        --entity {{ inventory_hostname }}
--
        {{ maas_rpc_scripts_dir }}/rpc-maas-tool.py verify-status
        --entity {{ inventory_hostname }}
```

##### What is actually happening?

See above 

##### How can we reproduce this issue?

Use short hostnames in the inventory and long hostnames on host level
and run through the MAAS life cycle

##### How can we verify your issue is addressed?

All playbooks run successfully when installing them and running the verify-maas.yml playbook

##### If this is a large issue, what can be done immediately to alleviate the issue while working on a longer-term solution?

Normal prio

##### What is your evaluation on the importance of this issue, and why?

None

----------------------------------------------------------------------------------------------------------------------------
###### For each pull request, update the branch line to reference it.
- [x] master
- [x] liberty-12.2
- [x] kilo

##### Upgrade impact. Consider the impact on moving between major, minor and patch releases.
- [x] This change does not impact upgrades
- [ ] This change addresses a potential upgrade impact
- [ ] The upgrade impact is being tracked by another issue.

The issue tracking the upgrade impact is:

##### Testing impact
- [x] An issue/pull-request has been create or exists to track the testing gap, and is referenced below
- [ ] This change includes additional testing
- [ ] This change is tested by the existing setup

Additional testing links: https://github.com/rcbops/u-suk-dev/issues/283

##### Release note
- [ ] This change includes a release note.
- [x] This change does not require a release note.

##### Does your change require documentation?
- [ ] Yes, and I submitted an issue to [Docs issues](https://github.com/rackerlabs/docs-rpc/issues "Docs issues")
- [ ] Yes, and I contributed a documentation patch to [docs-rpc](https://github.com/rackerlabs/docs-rpc "docs-rpc")
- [x] No documentation required for this change

Additional documentation links (please add links if you have ticked yes):

**Comment by d34dh0r53** [comment]
We should be consistent and use short hostnames everywhere.

**Comment by txgunslinger77** [comment]
This is the last play that is failing on the customer deploy I am working on, saying it can't find the entities. When I check the monitoring portal, the entities are all there and checking in 'green'. Here is a sample error from the deployment host:

TASK: [Verify Checks & Alarms are registered] *********************************
failed: [768028-cinder01] => {"attempts": 10, "changed": false, "failed": true, "failed_when_result": true, "rc": 1, "stdout_lines": ["Traceback (most recent call last):", "  File \"/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py\", line 618, in <module>", "    cli = RpcMassCli()", "  File \"/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py\", line 214, in __init__", "    self.args.raxrcpath)", "  File \"/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py\", line 55, in __init__", "    self._filter_entities()", "  File \"/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py\", line 70, in _filter_entities", "    raise Exception(\"No Entities found matching --entity or \"", "Exception: No Entities found matching --entity or --entitymatch"]}
stderr: OpenSSH_6.6.1, OpenSSL 1.0.1f 6 Jan 2014
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: mux_client_request_session: master session id: 2
Shared connection to 10.240.0.73 closed.

stdout: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py", line 618, in <module>
    cli = RpcMassCli()
  File "/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py", line 214, in __init__
    self.args.raxrcpath)
  File "/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py", line 55, in __init__
    self._filter_entities()
  File "/root/.ansible/tmp/ansible-tmp-1461191442.52-228658027580531/rpc-maas-tool.py", line 70, in _filter_entities
    raise Exception("No Entities found matching --entity or "
Exception: No Entities found matching --entity or --entitymatch


And here is the actual entity as it exists in the MaaS portal:

entity_label
    768028-cinder01.spindance.com

As I do not see the MaaS portal using anything but FQDN's for the near future, we should consider some other way to deal with that. For now, I'll be commenting out this play from deploy.sh until I hear otherwise.

Thanks

**Comment by BjoernT** [comment]
FYI this is still an issue with all releases since Kilo

**Comment by b3rnard0** [comment]
@claco @mancdaz Same questions, is this a feature and what is the size? That will drive when we do this.

**Comment by mancdaz** [comment]
@b3rnard0 if this can be reproduced, it's a bug rather than a feature

**Comment by BjoernT** [comment]
This is a bug and should be easily be reproducible.

**Comment by tomc603** [comment]
@nategraf is spinning up an environment to do some testing, and is currently in the discovery phase on this. @Frank-ZhangXin and @cloader89 has also offered help.

**Comment by cloader89** [comment]
I was able to reproduce the output in the original issue report. Going to see if I can reproduce the error in the comments.

**Comment by cloader89** [comment]
I propose that we use either inventory_hostname or ansible_hostname throughout, not using one somewhere, and the other somewhere else. What do you guys think?

**Comment by cloader89** [comment]
I would like more information @BjoernT, which SHA are you using?

**Comment by BjoernT** [comment]
This problem is existing in all versions of Kilo and Liberty. The particular SHA does not matter if you just look at the playbooks referencing different names. I suggest do change verify-maas to use the same variable as the Maas playbooks installing the checks. Other way around will cause havoc during upgrades

**Comment by cloader89** [comment]
Can you be specific as to which same variable?  @BjoernT

**Comment by b3rnard0** [comment]
@BjoernT Please provide feedback on the pull request at your earliest convenience. Thanks!

**Comment by Frank-ZhangXin** [comment]
Update: we have just built liberty and kilo backport for this patch, and wait the result.

**Comment by git-harry** [comment]
@nategraf remember that the checklist in the description needs to be completed. Currently the branches liberty-12.2 and kilo have been ticked but master hasn't, this doesn't match up with the pull requests. This idea is that the branches listed should be the ones requiring the fix and they should be ticked when the fix merges.
